
server:
  port: 8084
  servlet:
    context-path: /point
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.198.119:8848
        password: nacos
  application:
    name: point
  zipkin:
    base-url: http://localhost:9411/ # 服务端地址
    sender:
      type: web                      # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0

rocketmq:
  name-server: 114.132.198.119:9876
  producer:
    group: test-producer-group
  consumer:
    group: SpringBoot_Group
