
server:
  port: 8081
  servlet:
    context-path: /order
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.198.119:8848
        password: nacos
  application:
    name: order
  zipkin:
    base-url: http://localhost:9411/ # 服务端地址
    sender:
      type: web                      # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0