server:
  port: 8080

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.198.119:8848
        password: nacos
    gateway:
      routes:
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
    loadbalancer:
      cache:
        enabled: true

  application:
    name: gateway

