server:
  port: 8080

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.198.119:8848
        password: nacos
    gateway:
      routes:
        - id: goods
          uri: http://localhost:8081
          predicates:
            - Path=/goods/**
          filters:

  application:
    name: gateway

