server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.198.119:8848
        password: nacos
    gateway:
      routes:
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
    loadbalancer:
      cache:
        enabled: true
  zipkin:
    base-url: http://localhost:9411/ # 服务端地址
    sender:
      type: web                      # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0
